# Test configuration

components:
  obecny: obecny
  vmarchaud: vmarchaud
  dyladan: dyladan
  shared:
    - obecny
    - vmarchaud
    - dyladan

  obecny/vmarchaud: vmarchaud
  obecny/dyladan: dyladan
  vmarchaud/dyladan: dyladan
  vmarchaud/obecny: obecny
  dyladan/vmarchaud: vmarchaud
  dyladan/obecny: obecny